version: '3.7'
services:
  shiro-chan-server:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: EasternTalesShelf-fastapi-updater  # Custom container name
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - OAUTH_CLIENT_SECRET
      - VAULT_ADDR
      - VAULT_ROLE_ID_shiro_chan_project
      - VAULT_SECRET_ID_shiro_chan_project
      - FLASK_ENV
    networks:
      - phpmyadmin_gpt_db
    volumes:
      - ./app:/app  # Maps the app directory on your host to /app in your container
      - /home/ubuntu/docker/logs:/app/logs

networks:
  phpmyadmin_gpt_db:
    external: true
volumes:
  logs_volume:
